name: Test Custom
on:
  workflow_call:
    inputs:
      test-command:
        type: string
        required: true
      working-directory:
        type: string
        default: '.'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: Run tests
        run: ${{ inputs.test-command }}
